from fastapi import APIRouter, HTTPException, Form, File, UploadFile, Request
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
import json

router = APIRouter()

# Pydantic models
class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = 1000

class ChatResponse(BaseModel):
    message: str
    timestamp: str

class QuestionRequest(BaseModel):
    question: str
    temperature: Optional[float] = 0.7
    context: Optional[str] = ""
    uuid: Optional[str] = ""

# Markdown examples for different modes
MARKDOWN_EXAMPLES = {
    "general": """# Welcome to the AI Assistant! 🤖

This is a **comprehensive markdown example** that demonstrates various formatting options:

## Text Formatting
- **Bold text** and *italic text*
- ~~Strikethrough~~ and `inline code`
- [Links](https://example.com) and [email links](mailto:test@example.com)

## Lists
### Unordered List
- First item
- Second item
  - Nested item
  - Another nested item
- Third item

### Ordered List
1. First step
2. Second step
3. Third step

## Code Examples
```python
def hello_world():
    print("Hello, World!")
    return "Success"

# This is a comment
result = hello_world()
```

## Tables
| Feature | Status | Priority |
|---------|--------|----------|
| Authentication | Complete | High |
| Database | In Progress | High |
| UI Design | Pending | Medium |

## Blockquotes
> This is a blockquote example.
> It can span multiple lines and is great for highlighting important information.

## Horizontal Rules
---

## Special Characters
Special characters and symbols

## Mathematical Expressions (if supported)
E = mc²

## Task Lists
- [x] Completed task
- [ ] Pending task
- [ ] Another pending task

---
*This response was generated by the local backend API*""",

    "writing": """# Creative Writing Assistant

## Story Structure Example

### The Hero's Journey
1. **Ordinary World** - The protagonist's normal life
2. **Call to Adventure** - Something disrupts the status quo
3. **Refusal of the Call** - Initial hesitation
4. **Meeting the Mentor** - Guidance and wisdom
5. **Crossing the Threshold** - Entering the special world

## Character Development
> **Protagonist**: A complex character with:
> - Clear motivations
> - Internal conflicts
> - Character arc progression
> - Relatable flaws

## Dialogue Examples
"Hello there," she said with a warm smile.
"I've been waiting for you," he replied, his voice trembling slightly.

## Descriptive Writing
The old mansion stood silent against the stormy sky, its windows like dark eyes watching the world below. The wind howled through the broken shutters, creating an eerie symphony of creaks and groans.

## Writing Tips
- **Show, don't tell** - Use actions and dialogue
- **Use sensory details** - Engage all five senses
- **Vary sentence structure** - Mix short and long sentences
- **Create tension** - Keep readers engaged

## Common Writing Mistakes to Avoid
1. Overusing adverbs
2. Telling instead of showing
3. Flat characters
4. Info dumps
5. Weak dialogue

---
*Ready to help you craft your next masterpiece!*""",

    "code": """# Code Assistant & Developer Tools

## Programming Languages Overview

### Python Example
```python
class DataProcessor:
    def __init__(self, data: list):
        self.data = data
    
    def process(self) -> dict:
        \"\"\"Process the data and return statistics.\"\"\"
        return {
            'count': len(self.data),
            'sum': sum(self.data),
            'average': sum(self.data) / len(self.data) if self.data else 0
        }

# Usage
processor = DataProcessor([1, 2, 3, 4, 5])
result = processor.process()
print(result)
```

### JavaScript Example
```javascript
const fetchUserData = async (userId) => {
    try {
        const response = await fetch(`/api/users/${userId}`);
        const userData = await response.json();
        return userData;
    } catch (error) {
        console.error('Error fetching user:', error);
        throw error;
    }
};

// Usage with async/await
const user = await fetchUserData(123);
```

### SQL Queries
```sql
-- Complex query with joins and aggregations
SELECT 
    u.username,
    COUNT(p.id) as post_count,
    AVG(r.rating) as avg_rating
FROM users u
LEFT JOIN posts p ON u.id = p.user_id
LEFT JOIN ratings r ON p.id = r.post_id
WHERE u.created_at > '2024-01-01'
GROUP BY u.id, u.username
HAVING COUNT(p.id) > 5
ORDER BY avg_rating DESC;
```

## Development Best Practices

### Git Workflow
```bash
# Feature branch workflow
git checkout -b feature/new-feature
git add .
git commit -m "Add new feature"
git push origin feature/new-feature
```

### Testing
```python
import unittest

class TestDataProcessor(unittest.TestCase):
    def test_empty_data(self):
        processor = DataProcessor([])
        result = processor.process()
        self.assertEqual(result['count'], 0)
    
    def test_normal_data(self):
        processor = DataProcessor([1, 2, 3])
        result = processor.process()
        self.assertEqual(result['sum'], 6)
```

## Architecture Patterns
- **MVC** - Model-View-Controller
- **Repository Pattern** - Data access abstraction
- **Factory Pattern** - Object creation
- **Observer Pattern** - Event handling

---
*Your coding companion for all development needs!*""",

    "documentrag": """# Document RAG (Retrieval-Augmented Generation) 📄

## Document Processing Pipeline

### 1. Document Ingestion
```python
def process_document(file_path: str) -> dict:
    \"\"\"Process various document formats.\"\"\"
    if file_path.endswith('.pdf'):
        return extract_pdf_content(file_path)
    elif file_path.endswith('.docx'):
        return extract_docx_content(file_path)
    elif file_path.endswith('.txt'):
        return extract_text_content(file_path)
```

### 2. Text Chunking Strategy
- **Chunk Size**: 512-1024 tokens
- **Overlap**: 50-100 tokens
- **Boundary**: Sentence/paragraph breaks

### 3. Vector Embeddings
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(chunks)
```

## Document Types Supported

| Type | Extension | Processing Method |
|------|-----------|------------------|
| PDF | `.pdf` | PyPDF2/pdfplumber |
| Word | `.docx` | python-docx |
| Text | `.txt` | Direct reading |
| HTML | `.html` | BeautifulSoup |
| Markdown | `.md` | Markdown parser |

## RAG Query Process

### Step 1: Query Processing
```python
def process_query(query: str) -> str:
    # Clean and preprocess query
    cleaned_query = clean_text(query)
    return cleaned_query
```

### Step 2: Similarity Search
```python
def find_relevant_chunks(query_embedding, chunk_embeddings, top_k=5):
    similarities = cosine_similarity(query_embedding, chunk_embeddings)
    top_indices = similarities.argsort()[-top_k:][::-1]
    return top_indices
```

### Step 3: Context Assembly
```python
def assemble_context(relevant_chunks: list) -> str:
    context = "\n\n".join([chunk['content'] for chunk in relevant_chunks])
    return context
```

## Document Metadata
```json
{
    "document_id": "doc_123",
    "title": "Technical Manual",
    "author": "John Doe",
    "created_date": "2024-01-15",
    "file_type": "pdf",
    "chunk_count": 45,
    "total_tokens": 12500
}
```

## Search Results Format
```json
{
    "query": "machine learning algorithms",
    "results": [
        {
            "chunk_id": "chunk_001",
            "content": "Machine learning algorithms...",
            "similarity_score": 0.89,
            "document_title": "ML Guide",
            "page_number": 15
        }
    ],
    "total_results": 5
}
```

---
*Advanced document processing and retrieval capabilities!*"""
}

@router.post("/questions/general")
async def general_questions(request: Request):
    """Handle general questions with markdown examples"""
    try:
        # Try to parse as JSON first
        body = await request.json()
        question = body.get("question", "")
        temperature = body.get("temperature", 0.7)
        context = body.get("context", "")
        uuid = body.get("uuid", "")
    except:
        # Fall back to form data
        form = await request.form()
        question = form.get("question", "")
        temperature = float(form.get("temperature", 0.7))
        context = form.get("context", "")
        uuid = form.get("uuid", "")
    
    return {
        "message": MARKDOWN_EXAMPLES["general"],
        "status": "success"
    }

@router.post("/questions/write")
async def writing_questions(request: Request):
    """Handle writing-related questions with markdown examples"""
    try:
        # Try to parse as JSON first
        body = await request.json()
        question = body.get("question", "")
        temperature = body.get("temperature", 0.7)
        context = body.get("context", "")
        uuid = body.get("uuid", "")
    except:
        # Fall back to form data
        form = await request.form()
        question = form.get("question", "")
        temperature = float(form.get("temperature", 0.7))
        context = form.get("context", "")
        uuid = form.get("uuid", "")
    
    return {
        "message": MARKDOWN_EXAMPLES["writing"],
        "status": "success"
    }

@router.post("/questions/code")
async def code_questions(request: Request):
    """Handle code-related questions with markdown examples"""
    try:
        # Try to parse as JSON first
        body = await request.json()
        question = body.get("question", "")
        temperature = body.get("temperature", 0.7)
        context = body.get("context", "")
        uuid = body.get("uuid", "")
    except:
        # Fall back to form data
        form = await request.form()
        question = form.get("question", "")
        temperature = float(form.get("temperature", 0.7))
        context = form.get("context", "")
        uuid = form.get("uuid", "")
    
    return {
        "message": MARKDOWN_EXAMPLES["code"],
        "status": "success"
    }

@router.post("/questions/documentrag")
async def document_rag_questions(request: Request):
    """Handle document RAG questions with markdown examples"""
    try:
        # Try to parse as JSON first
        body = await request.json()
        question = body.get("question", "")
        temperature = body.get("temperature", 0.7)
        context = body.get("context", "")
        uuid = body.get("uuid", "")
    except:
        # Fall back to form data
        form = await request.form()
        question = form.get("question", "")
        temperature = float(form.get("temperature", 0.7))
        context = form.get("context", "")
        uuid = form.get("uuid", "")
    
    return {
        "message": MARKDOWN_EXAMPLES["documentrag"],
        "status": "success"
    }

@router.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """Chat endpoint for GenAI interactions - returns comprehensive markdown example"""
    try:
        # Create a comprehensive markdown showcase that includes all features
        comprehensive_markdown = """# Complete Markdown Showcase

This response demonstrates **all possible markdown features** that could be received from an LLM:

## Text Formatting
- **Bold text** for emphasis
- *Italic text* for subtle emphasis  
- ***Bold and italic*** combined
- ~~Strikethrough~~ for corrections
- `Inline code` for technical terms
- ==Highlighted text== (if supported)

## Links and References
- [External link](https://example.com)
- [Email link](mailto:test@example.com)
- [Internal reference](#heading-1)
- [Link with title](https://example.com "Tooltip text")

## Lists

### Unordered Lists
- First item
- Second item
  - Nested item
  - Another nested item
    - Deeply nested
- Third item

### Ordered Lists
1. First step
2. Second step
3. Third step
   1. Sub-step A
   2. Sub-step B
4. Fourth step

### Task Lists
- [x] Completed task
- [ ] Pending task
- [ ] Another pending task
- [x] Done task

## Code Examples

### Inline Code
Use `console.log()` for debugging in JavaScript.

### Code Blocks
```python
def fibonacci(n):
    \"\"\"Calculate Fibonacci sequence.\"\"\"
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

# Example usage
for i in range(10):
    print(f"F({i}) = {fibonacci(i)}")
```

```javascript
// Async/await example
const fetchData = async (url) => {
    try {
        const response = await fetch(url);
        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Error:', error);
        throw error;
    }
};

// Usage
fetchData('/api/data').then(data => {
    console.log('Received:', data);
});
```

```sql
-- Complex query with CTE
WITH monthly_sales AS (
    SELECT 
        DATE_TRUNC('month', order_date) as month,
        SUM(amount) as total_sales
    FROM orders 
    WHERE order_date >= '2024-01-01'
    GROUP BY DATE_TRUNC('month', order_date)
)
SELECT 
    month,
    total_sales,
    LAG(total_sales) OVER (ORDER BY month) as prev_month_sales,
    ROUND(
        (total_sales - LAG(total_sales) OVER (ORDER BY month)) / 
        LAG(total_sales) OVER (ORDER BY month) * 100, 2
    ) as growth_percentage
FROM monthly_sales
ORDER BY month;
```

## Tables

| Feature | Status | Priority | Notes |
|---------|--------|----------|-------|
| Authentication | Complete | High | JWT implemented |
| Database | In Progress | High | MongoDB setup |
| UI Design | Pending | Medium | Wireframes ready |
| API Testing | Not Started | Low | Need test suite |
| Documentation | Draft | Medium | 80% complete |

### Complex Table
| Language | Paradigm | Typing | Popularity | Best For |
|----------|----------|--------|------------|----------|
| Python | Multi-paradigm | Dynamic | ***** | Data Science, Web |
| TypeScript | Multi-paradigm | Static | ***** | Frontend, Node.js |
| Rust | Systems | Static | **** | Performance, Safety |
| Go | Imperative | Static | **** | Backend, DevOps |

## Blockquotes

> This is a simple blockquote.
> It can span multiple lines.

> **Important Note:** This is a blockquote with formatting.
> 
> It can contain:
> - Lists
> - **Bold text**
> - `Code snippets`

> > Nested blockquotes are also possible!
> > 
> > They create a nice visual hierarchy.

## Horizontal Rules

---

## Mathematical Expressions

Inline math: E = mc²

Block math:
```
∫₀^∞ e^(-x²) dx = √π/2
```

## Special Characters

### Common Symbols
Common symbols and special characters

### Technical Symbols
Technical symbols and indicators

### Status Indicators
Status indicators: Complete, Not Started, In Progress, Warning, Info, Pending

## HTML Elements (if supported)

<details>
<summary>Click to expand</summary>

This is collapsible content that can contain:
- Lists
- **Bold text**
- `Code snippets`
- [Links](https://example.com)

</details>

## Advanced Formatting

### Footnotes¹
This text has a footnote reference.

### Abbreviations
The <abbr title="HyperText Markup Language">HTML</abbr> specification.

### Keyboard Shortcuts
Press <kbd>Ctrl</kbd> + <kbd>C</kbd> to copy.

### Subscripts and Superscripts
H₂O and E=mc²

## Alignment and Spacing

| Left Aligned | Center Aligned | Right Aligned |
|:-------------|:--------------:|--------------:|
| Left         | Center         | Right         |
| Text         | Text           | Text          |

## Special Features

### Definition Lists
Term 1
: Definition 1

Term 2
: Definition 2a
: Definition 2b

### Admonitions (if supported)
!!! note "Note"
    This is a note block with important information.

!!! warning "Warning"
    This is a warning block.

!!! tip "Tip"
    This is a helpful tip.

---

## Summary

This comprehensive example showcases:
- All text formatting options
- Multiple list types
- Code blocks with syntax highlighting
- Complex tables
- Blockquotes and nested content
- Mathematical expressions
- Special characters and symbols
- HTML elements and advanced features
- Proper spacing and alignment

*This response was generated by the backend API to demonstrate all possible markdown features that an LLM might return.*"""

        return ChatResponse(
            message=comprehensive_markdown,
            timestamp=datetime.now().isoformat()
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/models")
async def list_models():
    """List available GenAI models"""
    return {
        "models": [
            {"id": "local-dummy", "name": "Local Dummy API"},
            {"id": "markdown-examples", "name": "Markdown Examples Generator"}
        ]
    }

@router.get("/api/test")
async def test_endpoint():
    """Test endpoint for health checks"""
    return {"status": "success", "message": "Backend API is running"}
